### ISSUE TITLE
Content assist broken with this grammar

### ISSUE THREAD

**Issue by ydaveluy** [eclipse-langium/langium#1636] opened 2024-08-17 09:33 UTC
The content assist is broken when using `/"[^"]*"/` for ID instead of `/[_a-zA-Z][\w_]*/`.

Langium version: 3.1.0
Package name:3.1.3

## Steps To Reproduce

1. Put this grammar in the Playground
```
grammar HelloWorld

entry Model:
    (persons+=Person | greetings+=Greeting)*;

Person:
    'person' name=ID;

Greeting:
    'Hello' person=[Person:ID] '!';

hidden terminal WS: /\s+/;
terminal ID: /"[^"]*"/; // use quote instead of /[_a-zA-Z][\w_]*/

hidden terminal ML_COMMENT: /\/\*[\s\S]*?\*\//;
hidden terminal SL_COMMENT: /\/\/[^\n\r]*/;

```
2. start typing `pe` in an empty editor

## The current behavior
The content assist provides `person` **and** `Hello` choices instead of `person` only. 

When selecting the element `person` from the content assist it produces `peperson` instead of `person`.

## The expected behavior

Same as default HelloWorld grammar.

**Comment by msujew** [comment] 2024-08-17 10:02
Duplicate of https://github.com/eclipse-langium/langium/issues/1347. The linked issue contains a bunch of discussion on why we cannot support this (at least with how we currently identify tokens).

**Closed by msujew** 2024-08-17 10:02 UTC
Labels: bug

**Comment by ydaveluy** [comment] 2024-09-13 15:51
Hey @msujew,

FYI I finally found how to fix this issue by overriding the token builder : https://github.com/ydaveluy/xsmp-modeler/blob/e53e81b72d59dfc243e2e7bc0f4c70ed3eb07ebf/src/language/parser/xsmpproject-token-builder.ts#L4

I don't know if a more generic approach  could be integrated in Langium but it works well in my specific case.

**Comment by msujew** [comment] 2024-09-13 16:42
@ydaveluy why not have an ID terminal that allows lower case starting letter and a validation that tells the user that IDs are supposed to start with an upper case letter (similar to how we do it in the hello-world grammar from the yeoman generator)? That resolves the issue without resorting to workarounds.

**Comment by ydaveluy** [comment] 2024-09-13 16:50
Because in my grammar the IDs are between quotes ( `/"[^"]*"/`), I should have rename the rule to STRING in the example.

I tried to add an other terminal rules ID2: `/\w+/` but the rule is unused and skipped by the token builder.

**Comment by msujew** [comment] 2024-09-13 16:54
Ah right, I mixed it up with the grammar in https://github.com/eclipse-langium/langium/issues/1347. I guess that makes sense. Thanks for posting a potential solution for this!
